# Generated by Django 5.2.7 on 2025-11-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('cupcake', 'Cupcake'), ('forest', 'Forest'), ('dracula', 'Dracula'), ('cyberpunk', 'Cyberpunk'), ('synthwave', 'Synthwave'), ('retro', 'Retro')], default='light', max_length=50),
        ),
    ]
