# Generated by Django 5.2.7 on 2025-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Bright'), ('dark', 'Night'), ('cupcake', 'Cupcake'), ('forest', 'Nature'), ('dracula', 'Dracula'), ('cyberpunk', 'Neon'), ('synthwave', 'Retro Wave'), ('retro', 'Vintage')], default='light', max_length=50),
        ),
    ]
