# Generated by Django 5.2.7 on 2025-12-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_avatar_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='link',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('profile', 'position')},
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['position'], name='profiles_li_positio_90e329_idx'),
        ),
    ]
