# Generated by Django 5.2.7 on 2025-12-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_link_options_link_position_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='link',
            name='profiles_li_positio_90e329_idx',
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='link',
            name='position',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
