# Generated by Django 5.2.7 on 2025-12-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_link_profiles_li_positio_90e329_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
